version: '3.8'
services:
  frontend:
    image: ${EAL_FRONTEND_IMAGE}
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.eal.rule=Host(`lindsay.heatherward.dev`,`www.lindsay.heatherward.dev`)"
      - "traefik.http.routers.eal.entrypoints=https"
      - "traefik.http.routers.eal.tls.certresolver=cloudflaredns"
      - "traefik.http.services.eal.loadbalancer.server.port=80"
    networks:
      - proxy
    volumes:
      - ${EAL_SRV_BASE}/sites-available:/etc/nginx/sites-enabled
networks:
  proxy:
    external: true